// Bosnia / Sandžak locations used by vaktija.ba API.
// The "id" is the numeric location id consumed by the API endpoint:
//   https://api.vaktija.ba/vaktija/v1/:id
export const LOCATIONS = [
  { id: 1, name: "Banovići" },
  { id: 2, name: "Banja Luka" },
  { id: 3, name: "Bihać" },
  { id: 4, name: "Bijeljina" },
  { id: 5, name: "Bileća" },
  { id: 6, name: "Bosanski Brod" },
  { id: 7, name: "Bosanska Dubica" },
  { id: 8, name: "Bosanska Gradiška" },
  { id: 9, name: "Bosansko Grahovo" },
  { id: 10, name: "Bosanska Krupa" },
  { id: 11, name: "Bosanski Novi" },
  { id: 12, name: "Bosanski Petrovac" },
  { id: 13, name: "Bosanski Šamac" },
  { id: 14, name: "Bratunac" },
  { id: 15, name: "Brčko" },
  { id: 16, name: "Breza" },
  { id: 17, name: "Bugojno" },
  { id: 18, name: "Busovača" },
  { id: 19, name: "Bužim" },
  { id: 20, name: "Cazin" },
  { id: 21, name: "Čajniče" },
  { id: 22, name: "Čapljina" },
  { id: 23, name: "Čelić" },
  { id: 24, name: "Čelinac" },
  { id: 25, name: "Čitluk" },
  { id: 26, name: "Derventa" },
  { id: 27, name: "Doboj" },
  { id: 28, name: "Donji Vakuf" },
  { id: 29, name: "Drvar" },
  { id: 30, name: "Foča" },
  { id: 31, name: "Fojnica" },
  { id: 32, name: "Gacko" },
  { id: 33, name: "Glamoč" },
  { id: 34, name: "Goražde" },
  { id: 35, name: "Gornji Vakuf" },
  { id: 36, name: "Gračanica" },
  { id: 37, name: "Gradačac" },
  { id: 38, name: "Grude" },
  { id: 39, name: "Hadžići" },
  { id: 40, name: "Han-Pijesak" },
  { id: 41, name: "Hlivno" },
  { id: 42, name: "Ilijaš" },
  { id: 43, name: "Jablanica" },
  { id: 44, name: "Jajce" },
  { id: 45, name: "Kakanj" },
  { id: 46, name: "Kalesija" },
  { id: 47, name: "Kalinovik" },
  { id: 48, name: "Kiseljak" },
  { id: 49, name: "Kladanj" },
  { id: 50, name: "Ključ" },
  { id: 51, name: "Konjic" },
  { id: 52, name: "Kotor-Varoš" },
  { id: 53, name: "Kreševo" },
  { id: 54, name: "Kupres" },
  { id: 55, name: "Laktaši" },
  { id: 56, name: "Lopare" },
  { id: 57, name: "Lukavac" },
  { id: 58, name: "Ljubinje" },
  { id: 59, name: "Ljubuški" },
  { id: 60, name: "Maglaj" },
  { id: 61, name: "Modriča" },
  { id: 62, name: "Mostar" },
  { id: 63, name: "Mrkonjić-Grad" },
  { id: 64, name: "Neum" },
  { id: 65, name: "Nevesinje" },
  { id: 66, name: "Novi Travnik" },
  { id: 67, name: "Odžak" },
  { id: 68, name: "Olovo" },
  { id: 69, name: "Orašje" },
  { id: 70, name: "Pale" },
  { id: 71, name: "Posušje" },
  { id: 72, name: "Prijedor" },
  { id: 73, name: "Prnjavor" },
  { id: 74, name: "Prozor" },
  { id: 75, name: "Rogatica" },
  { id: 76, name: "Rudo" },
  { id: 77, name: "Sanski Most" },
  { id: 78, name: "Sarajevo" },
  { id: 79, name: "Skender-Vakuf" },
  { id: 80, name: "Sokolac" },
  { id: 81, name: "Srbac" },
  { id: 82, name: "Srebrenica" },
  { id: 83, name: "Srebrenik" },
  { id: 84, name: "Stolac" },
  { id: 85, name: "Šekovići" },
  { id: 86, name: "Šipovo" },
  { id: 87, name: "Široki Brijeg" },
  { id: 88, name: "Teslić" },
  { id: 89, name: "Tešanj" },
  { id: 90, name: "Tomislav-Grad" },
  { id: 91, name: "Travnik" },
  { id: 92, name: "Trebinje" },
  { id: 93, name: "Trnovo" },
  { id: 94, name: "Tuzla" },
  { id: 95, name: "Ugljevik" },
  { id: 96, name: "Vareš" },
  { id: 97, name: "Velika Kladuša" },
  { id: 98, name: "Visoko" },
  { id: 99, name: "Višegrad" },
  { id: 100, name: "Vitez" },
  { id: 101, name: "Vlasenica" },
  { id: 102, name: "Zavidovići" },
  { id: 103, name: "Zenica" },
  { id: 104, name: "Zvornik" },
  { id: 105, name: "Žepa" },
  { id: 106, name: "Žepče" },
  { id: 107, name: "Živinice" },
  { id: 108, name: "Bijelo Polje" },
  { id: 109, name: "Gusinje" },
  { id: 110, name: "Nova Varoš" },
  { id: 111, name: "Novi Pazar" },
  { id: 112, name: "Plav" },
  { id: 113, name: "Pljevlja" },
  { id: 114, name: "Priboj" },
  { id: 115, name: "Prijepolje" },
  { id: 116, name: "Rožaje" },
  { id: 117, name: "Sjenica" },
  { id: 118, name: "Tutin" },
];

export function findLocationNameById(id) {
  const match = LOCATIONS.find((l) => l.id === Number(id));
  return match ? match.name : "";
}


